### ISSUE TITLE
Excluir patologia ou procedimento de um atendimento

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#185]
Permitir que o aluno responsável possa excluir uma patologia ou procedimento de um atendimento que ainda esteja em andamento.
Permitir que o professor supervisor possa excluir uma patologia ou procedimento de um atendimento que esteja em andamento ou realizado.

Solicitar a confirmação da exclusão

**Comment by lucasvss** [comment]
Como aluno é possível excluir uma patologia ou procedimento de um atendimento que está em andamento. 

Como aluno é mostrado a opção de excluir procedimento quando o atendimento está realizado algo que não deveria ser mostrado.

Como professor não está sendo mostrado a opção de excluir uma patologia quando o atendimento está em andamento ou realizado. 

Como professor a opção de excluir procedimento é mostrada quando o atendimento está em andamento ou realizado mas ao tentar excluir não é mostrado a confirmação de exclusão e assim não é possível realizar a exclusão.

**Comment by lucasvss** [comment]
A exclusão de uma patologia ou procedimento pelo aluno está funcionando corretamente onde só podem ser excluídos quando o atendimento está em andamento.

A exclusão de uma patologia ou procedimento pelo professor responsável também está funcionando corretamente onde só podem ser excluídos quando o atendimento está em andamento ou realizado.
