### ISSUE TITLE
Excluir atendimento

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#186]
Permitir que o aluno responsável possa excluir um atendimento em andamento, excluindo também todas as patologias e procedimento relacionados a ele.
Solicitar confirmação de exclusão

**Comment by lucasvss** [comment]
Ao tentar excluir um atendimento em andamento é exibido um modal de confirmação e ao confirmar a exclusão o atendimento é excluído e todas as patologias e procedimentos relacionados ao atendimento também são excluídas conforme o esperado.
