### ISSUE TITLE
Alterar visualização do botão de finalizar/validar na página de detalhe do atendimento

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#187]
Incluir a descrição do status do atendimento e colocar um botão para finalizar o atendimento (na visão do alunos) ou validar o atendimento (na visão do professor), pois da forma atual está confuso.
 
![prontuario_aluno.png](https://zube.io/files/npi-ufc-qxd/506cc0d8aa40099bdac5dc888b5a4b1c.png)
![prontuario_professor.png](https://zube.io/files/npi-ufc-qxd/744a379f8cb309cd4d11e24a1ba8a7b2.png)

**Comment by lucasvss** [comment]
Descrição do status do atendimento e botão para finalizar ou validar o atendimento estão inseridos conforme especificado.
