### ISSUE TITLE
Incluir um novo plano de tratamento para um paciente

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#188]
Eu como Atendente gostaria de incluir uma clínica no plano de tratamento de um paciente.
* Deve ser informada a **clínica** e a **prioridade** do tratamento. A prioridade vai de 1 (mais urgente) a 5 (menos urgente).
* Ao incluir o tratamento, salvar a **data de inclusão** e o **responsável** que realizou a inclusão.
* O paciente só pode possuir um tratamento em andamento por clínica.
* O status inicial deve ser **aguardando**

**Comment by lucasvss** [comment]
Ao incluir um novo plano de tratamento de um paciente está sendo exibido os campos para selecionar qual clínica e qual prioridade para aquele tratamento.

O tratamento está sendo salvo e a data de inclusão e o responsável estão sendo inseridos junto com o status inicial "aguardando" conforme especificado.

**Comment by virginiafarias** [comment]
Atualização da história:

* O status inicial deve ser **em espera**

**Comment by lucasvss** [comment]
A inclusão do tratamento está sendo realizada conforme o especificado sendo atribuída o status de em espera ao incluir o tratamento.
