### ISSUE TITLE
Visualizar plano de tratamento de um paciente

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#189]
Eu como Usuário do sistema gostaria de visualizar o plano de tratamento de um paciente.
* Deve ser mostrada uma lista com todos os tratamentos do paciente, exibindo a clínica, prioridade, status, data de inclusão e responsável pela inclusão.

**Comment by lucasvss** [comment]
Lista com todos os tratamentos de um certo paciente está sendo mostrada com os dados especificados.
