### ISSUE TITLE
Excluir um plano de tratamento para um paciente

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#190]
Eu como Atendente gostaria de excluir um tratamento de um paciente.
* Só deve ser permitida a exclusão de tratamento ainda não finalizados.

**Comment by lucasvss** [comment]
Não está sendo realizada a exclusão do tratamento.

**Comment by lucasvss** [comment]
É permitido excluir um tratamento de um paciente mas ao tentar excluir mais de um tratamento o modal não é aberto para confirmar a exclusão.

**Comment by lucasvss** [comment]
A exclusão está sendo realizada conforme o especificado.

**Comment by virginiafarias** [comment]
Atualização da história:
* Só deve ser permitida a exclusão de tratamento **em espera**.

**Comment by lucasvss** [comment]
Está sendo realizada a exclusão com status diferentes de em espera algo que não deveria ser permitido.

**Comment by lucasvss** [comment]
A exclusão só está sendo permitida quando o status do tratamento está em espera.
