### ISSUE TITLE
Visualizar pacientes aguardando tratamento

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#192]
Eu como Usuário gostaria de visualizar todos os paciente que estão aguardando tratamento para uma determinada clínica.
* Mostrar uma lista com o nome do paciente e a prioridade do tratamento para a clínica selecionada.

**Comment by lucasvss** [comment]
Não está sendo mostrado a lista com os pacientes que estão aguardando tratamento.

**Comment by lucasvss** [comment]
Listagem dos pacientes que estão aguardando tratamento está sendo realizada com sucesso.

**Comment by virginiafarias** [comment]
Atualização da história:
Eu como Usuário gostaria de visualizar todos os paciente que possuem plano de tratamento.
* Permitir que possa ser selecionada a clínica e o status do plano de tratamento. A seleção da clínica é obrigatória.
* Mostrar uma lista com o nome do paciente, a prioridade e o status do tratamento para a clínica selecionada.

**Comment by lucasvss** [comment]
Está sendo listado os pacientes que possuem um plano de tratamento com as seguintes informações o nome do paciente, a prioridade e o status do tratamento conforme o especificado.

**Comment by lucasvss** [comment]
Está sendo listado os pacientes que possuem um plano de tratamento conforme o especificado.
