### ISSUE TITLE
Permitir definir a ordem d as perguntas da anamnese

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#207]
Ao cadastrar as perguntas na anamnese, permitir que possa ser informada a ordem de exibição das perguntas.
Na realização e visualização da anamnese mostrar na ordem estabelecida no cadastro.

**Comment by lucasvss** [comment]
As perguntas estão sendo reorganizadas conforme a escolha do usuário e está sendo finalizada a anamnese. Uma possível melhoria é retirar o evento de reordenação das perguntas após a anamnese ser finalizada.

**Comment by lucasvss** [comment]
Existe um bug ao utilizar o sistema no firefox que ao trocar a posição de uma pergunta com a última pergunta a troca não é realizada.
