### ISSUE TITLE
Melhorar seleção de patologias e procedimentos no odontograma

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#210]
A seleção de patologias ou procedimentos no odontograma fica com uma usabilidade muito ruim porque existem muitas opções para selecionar e não é possível realizar uma busca pelo que o usuário quer já que a seleção é feita através de checkbox.

**Comment by lucasvss** [comment]
A seleção das patologias está sendo realizada através de um campo de pesquisa onde é possível realizar a busca por patologias digitando o nome da patologia e assim melhorando a usabilidade que havia antes.
