### ISSUE TITLE
Remover componente de data e incluir máscara nos campos de data em todo o sistema

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#211]

**Comment by lucasvss** [comment]
Não está sendo realizado o cadastro pois quando é clicado no campo data e deixado o campo vazio duas barras são aidiconados ao campo e devido a isso é emitido um erro ao tentar cadastrar

**Comment by lucasvss** [comment]
Não está sendo permitido colocar datas válidas.

**Comment by lucasvss** [comment]
Ainda persiste o erro quando é inserido duas barras, além de permitir inserir um único número e assim ocasionando novamente o erro.

Devido ao alert a usabilidade ao cadastrar um paciente acaba sendo prejudica.

Uma possível solução é a remoção desse alert.

**Comment by lucasvss** [comment]
Os componentes de data foram removidos e máscara de data foi incluída em todos os campos de data do sistema incluindo também uma verificação se as datas são válidas ou não.
