### ISSUE TITLE
Incluir opção de criar e encerrar atendimento no odontograma

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#212]
No odontograma, ao invés de exibir mensagem sobre o atendimento, adicionar opção para incluir e finalizar atendimento para o aluno.

**Comment by lucasvss** [comment]
As opções de incluir um novo tratamento e finalizar atendimento estão sendo mostradas, ao finalizar um atendimento a opção para incluir um novo atendimento é exibida e ao adicionar um novo atendimento a opção de finalizar o atendimento é exibida.
