### ISSUE TITLE
Permitir que o aluno possa alterar um atendimento enquanto ele estiver andamento

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#213]

**Comment by lucasvss** [comment]
Ao tentar alterar um atendimento os dados já cadastrados não estão sendo exibidos para efetuar a alteração. Não está sendo exibido o professor cadastrado, não está sendo exibido o auxiliar cadastrado e não está sendo exibida a data cadastrada.

Não está sendo possível alterar o auxiliar pois o select vem com a opção nenhum e quando é feita a alteração o atendimento fica sem auxiliar.

**Comment by lucasvss** [comment]
Ao deixar o campo de data sem preenchimento e preencher os demais campos preenchidos é realizado a alteração mas é exibido uma página de erro pois o atendimento precisa possuir uma data.

Ao deixar o campo de professor ou turma sem seleção e permitido efetuar a edição mas um erro é mostrado.
