### ISSUE TITLE
Mudar forma de tratar uma patologia

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#214]
Incluir as patologias do dente ou face selecionados no odontograma quando o usuário for adicionar procedimento para que ele possa informar se aquelas patologias foram tratadas.

**Comment by virginiafarias** [comment]
Deixar a funcionalidade de tratar como está atualmente e incluir essa nova maneira.

**Comment by lucasvss** [comment]
As patologias estão sendo marcadas como tratadas quando são incluídas ao adicionar um procedimento conforme esperado.
