### ISSUE TITLE
Modificar botoes de excluir patologia e procedimento

### ISSUE THREAD

**Issue by gustavoaires** [npi-ufc-qxd/prontuario#219]
Colocar botao vermelho e com lixeira.

**Comment by gustavoaires** [comment]
muda os botões de excluir e finalizar plano de tratamento pra ficar padronizado com os outros botões do sistema, colocando ícones.

**Comment by gustavoaires** [comment]
botões em uma mesma coluna sem necessidade de colocar o nome na coluna

**Comment by gustavoaires** [comment]
com a mudança da alteração de status, não precisa ter a opção de finalizar. Apenas a de editar, já que o concluído é um dos status

**Comment by gustavoaires** [comment]
Cria uma opção para edição

**Comment by gustavoaires** [comment]
muda o nome de tratamento pra PLANO

**Comment by gustavoaires** [comment]
só pode editar quando o plano tem status em andamento ou em espera

**Comment by lucasvss** [comment]
Não está sendo realizado a alteração de status para concluído e nem para interrompido.

**Comment by lucasvss** [comment]
A prioridade e o status estão sendo alterado conforme o especificado e não podendo alterar quando o plano está concluído ou interrompido.
