### ISSUE TITLE
Gerenciar papéis de servidores

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#220]
* Alterar o menu de professores para servidores
* Permitir cadastrar/editar servidor informando quais papéis ele possui (PROFESSOR, ADMINISTRAÇÃO, ATENDENTE). Deve ser obrigatório o cadastro de pelo menos um papel.
* Somente o administrador pode gerenciar servidores.
Exibir os papéis na lista de servidores.

**Comment by lucasvss** [comment]
Melhoria: Está selecionado como default só o papel que o servidor possui.
Redirecionar para a página de edição quando for tentar editar sem selecionar nenhum papel.
O siape deve receber somente números.

**Comment by lucasvss** [comment]
O cadastro e alteração dos Servidores estão sendo realizadas com sucesso como esperado.
