### ISSUE TITLE
Permitir que o administrador possa visualizar todos os atendimentos de uma turma e de um aluno e visualizar todas as informações de um paciente (anamneses, atendimentos, odontograma, atendimentos, arquivos)

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#222]

**Comment by lucasvss** [comment]
Os atendimentos das turmas e dos alunos estão sendo visualizados, as informações do pacientes também estão sendo mostradas (anamneses, atendimentos, odontograma, atendimentos, arquivos).

**Comment by lucasvss** [comment]
Correção, como administrador não está sendo permitido a visualização de todas as informações de um paciente.

**Comment by lucasvss** [comment]
Os atendimentos das turmas e dos alunos estão sendo visualizados, as informações do pacientes também estão sendo mostradas (anamneses, atendimentos, odontograma, atendimentos, arquivos).
