### ISSUE TITLE
Enviar lembrete de atendimentos via email

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#224]
* Enviar email para os alunos que possuem atendimento em andamento informando que eles precisam finalizar o atendimento.
* Enviar email para os professores que possuem atendimento aguardando avaliação informando que eles precisam realizar a avaliação de atendimento.
* Fazer a verificação uma vez ao dia.

**Comment by lucasvss** [comment]
E-mail está sendo enviado informando para o aluno que tem um atendimento em andamento e precisa finalizá-lo e e-mail está sendo enviado para o professor informando que tem um atendimento que está aguardando avaliação.
