### ISSUE TITLE
Criar uma avaliação de atendimento

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#225]
Eu como Administrador gostaria de criar uma avaliação para os atendimentos de pacientes.
* Essa avaliação definirá os critérios que serão avaliados em cada atendimento.
* Uma avaliação deverá ter um nome, um status (ativa ou inativa) e uma lista de critérios de avaliação. Todos os itens são obrigatórios e deverá haver pelo menos um critério de avaliação.
* Os critérios de avaliação deverão ter um nome e um peso.
* Só poderá existir uma única avaliação ativa.
* Ao cadastrar uma avaliação, o status inicial dela deverá ser ativa e o nome e critérios deverão ser cadastrados em maiúsculo.

**Comment by lucasvss** [comment]
A avaliação está sendo adicionando conforme esperado onde ao cadastrar uma nova avaliação é preciso informar pelo menos um critério de avaliação que possui um nome e um peso e não é permitido cadastrar uma nova avaliação se já tiver uma avaliação ativa.
