### ISSUE TITLE
Realizar/alterar avaliação de atendimento

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#228]
Eu como Professor gostaria de realizar a avaliação de um atendimento do qual sou responsável.
* O professor deverá informar obrigatoriamente uma nota de 1 a 10 para cada critério da avaliação que está ativa. Poderá também inserir observações na avaliação.
* Deverá ser salva automaticamente a data de realização/alteração da avaliação.
* O professor só poderá avaliar atendimentos de turmas que estiverem ativas.

**Comment by lucasvss** [comment]
A avaliação está sendo realizada conforme especificado onde é possível atribuir uma nota de 0 a 10 para cada item e uma observação além de ser salva a data de realização e alteração da avaliação.
