### ISSUE TITLE
Visualizar avaliação de atendimento

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#229]
Eu como aluno ou auxiliar responsável, professor responsável ou administrador gostaria de visualizar a avaliação de um atendimento.
* Deverão ser exibidos os critérios de avaliação com suas respectivas notas, a média aritmética das notas, a data de realização/alteração e a observação.

**Comment by lucasvss** [comment]
Os dados da avaliação estão sendo exibidos para o aluno responsável, aluno auxiliar, para o professor responsável e para o administrador, conforme esperado.
