### ISSUE TITLE
Listar avaliações de atendimento

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/prontuario#234]
Eu como Administrador gostaria de listar todas as avaliações de atendimentos já criadas.
* Mostrar lista com todas as avaliações e seus respectivos atributos: nome, status e critérios
* A avaliação ativa deve ficar em destaque

**Comment by lucasvss** [comment]
As avaliações estão sendo listadas conforme esperado exibindo o nome status e os critérios daquela avaliação.
